### ISSUE TITLE
retrying using stream

### ISSUE THREAD

**Issue by dauledk** [debitoor/request-retry-stream#3]
In the readme it states "There is support for POST, PUT, DELETE and PATCH retrying using callbacks but not streaming". 

What does this mean? 

Specifying max attempts then only makes sense if using callbacks, and not streams?

Sorry if I misunderstood something :)

**Comment by ebdrup** [comment]
Streaming a POST request. Where you stream the content to upload is not supported. 

GET Streams can actually be retried because the straming of data doesn't start until after the http headers. So for example a 503 is retried. This is where most errors happen. 

You are correct that if streaming of data has started, it will not be retried. It will error with a premature close error or similar.

**Comment by dauledk** [comment]
Thanks for the good explanation, I will give it another try 👍
